---
# ansible-playbook ./main.yaml -i localhost, --ask-become
- name: bootstrap nix environment.
  hosts: all
  pre_tasks:
    - name: update installer cache if needed.
      package:
        upgrade: yes
        update_cache: true
        cache_valid_time: 86400
      become: true
  tasks:
    - name: install common programs.
      package:
        name:
          - git
      become: true

    - name: get git branch
      local_action: ansible.builtin.command git rev-parse --abbrev-ref HEAD
      run_once: true
      register: branch_name
      changed_when: false

    - name: clone nixos repo.
      ansible.builtin.git:
        repo: https://github.com/Velasko/Nixos
        dest: ~/Nixos
        version: "{{ branch_name.stdout }}"
        force: true
        single_branch: true

    - name: script downloading
      ansible.builtin.get_url:
        url: https://nixos.org/nix/install
        dest: /tmp/nix_install.sh
        mode: "0700"
      changed_when: false

    - name: create /nix
      ansible.builtin.file:
        path: /nix
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0755"
        state: directory
      become: true

    - name: executing script
      ansible.builtin.command:
        cmd: /tmp/nix_install.sh --no-daemon
        creates: /nix/store

    - name: adding home-manager channel
      ansible.builtin.lineinfile:
        path: ~/.nix-channels
        create: true
        line: "{{ item }}"
      with_items:
        - https://nixos.org/channels/nixos-24.11 nixpkgs
        - https://github.com/nix-community/home-manager/archive/release-24.11.tar.gz home-manager

    - name: nix allowUnfree
      ansible.builtin.lineinfile:
        path: ~/.config/nixpkgs/config.nix
        create: true
        line: "{ allowUnfree = true; }"

    - name: updating channels
      ansible.builtin.command:
        cmd: ~/.nix-profile/bin/nix-channel --update
      changed_when: false

    - name: clean up gtk files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - ~/.gtkrc-2.0
        - ~/.config/gtkrc
        - ~/.config/gtkrc-2.0
        - ~/.config/gtk-3.0/
        - ~/.config/gtk-4.0/

    - name: bootstraping home-manager
      ansible.builtin.command:
        # cmd: nix-shell '<home-manager>' -A install
        argv:
          - nix
          - --extra-experimental-features "nix-command flakes
          - run home-manager/release-24.11 -- init --switch
        creates: "~/.nix-profile/bin/home-manager"
      register: hm_install

    # - debug: var=hm_install
