---
- name: Bootstraping nix environment
  hosts: localhost
  connection: local
  tasks:
  - name: Script downloading
    ansible.builtin.get_url:
      url: https://nixos.org/nix/install
      dest: /tmp/nix_install.sh
      mode: '0700'
    changed_when: false

  - name: Executing script
    ansible.builtin.command:
      cmd: /tmp/nix_install.sh --no-daemon
      creates: /nix


