---
- name: Bootstraping nix environment
  hosts: localhost
  connection: local
  tasks:
  - name: Script downloading
    ansible.builtin.get_url:
      url: https://nixos.org/nix/install
      dest: /tmp/nix_install.sh
      mode: '0700'
    changed_when: false

  - name: Executing script
    ansible.builtin.command:
      cmd: /tmp/nix_install.sh --no-daemon
      creates: /nix

  - name: Adding home-manager channel
    ansible.builtin.blockinfile:
      path: ~/.nix-channels
      block: |
        https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

  - name: Updating channels
    ansible.builtin.command:
      cmd: nix-channel --update
    changed_when: false

  - name: Bootstraping home-manager
    ansible.builtin.command:
      cmd: nix-shell '<home-manager>' -A install
      creates: "/home/{{ ansible_user_id }}/.config/home-manager/home.nix"
    register: hm_install

  - debug: var=hm_install
